Groceries<-read.transactions(file.choose(),sep = ",")
install.packages("arulesViz")
install.packages("arules")
library(arules)
library(arulesViz)
itemFrequencyPlot(Groceries,topN =20,support = 0.001)
rules<-apriori(Groceries,parameter = list(support=0.001 ,confidence = 0.8))
rules
options(digits=2)
rules<-sort(rules,by="lift",decreasing = TRUE)
inspect(rules[1:5])
summary(rules)
plot(rules,method="graph",interactive=TRUE,shading=NA)
itemFrequency(Groceries[ ,1:6 ])
